#!/usr/bin/env python3
# Owned by vertex-order/kit — edit here. Vendored elsewhere via sync.toml;
# don't edit the copy there.
"""Inline every Design Component file so a page works from file://.

An entry page pulls in sibling components via <dc-import>. The DC runtime
(support.js) resolves those by `fetch()`, which browsers block on file://
origins ("CORS request not http"). Over http (GitHub Pages, `just serve`,
Claude Design) the fetch works fine, so an entry page loads `components.js`
only when `location.protocol` is `file:` — over http(s) the runtime always
fetches each `*.dc.html` live and a stale bundle can't cause wrong rendering.

This regenerates `site/components.js` — a plain <script> (loads on file://)
that pre-populates `window.__resourceBlobs[...]` with each component's
source, the cache the runtime checks before it fetches. So the .dc.html
files stay the single source of truth; this is a derived build artifact,
regenerated by the pre-commit hook, `just build`, and verified in CI by
`.github/workflows/check-generated.yml`.

Entry pages are detected, not configured: an entry page is any `site/*.dc.html`
that references `components.js` (it loads the bundle itself, so it must not be
inlined into it). Components never reference `components.js`. This lets the
same script run unchanged in every repo — the convention is `page.dc.html`,
but nothing here depends on that name.

No external deps. Run: python3 scripts/bundle-components.py
"""
import json
import sys
from pathlib import Path

SITE = Path(__file__).resolve().parent.parent / "site"
OUT = SITE / "components.js"


def is_entry_page(path):
    return "components.js" in path.read_text(encoding="utf-8")


COMPONENTS = sorted(p for p in SITE.glob("*.dc.html") if not is_entry_page(p))


def main():
    entries = {}
    for path in COMPONENTS:
        # Key must match support.js ensureFetched(): COMPONENT_DIR ("." ) +
        # "/" + encodeURIComponent(name) + ".dc.html".
        key = "./" + path.name
        entries[key] = path.read_text(encoding="utf-8")

    body = json.dumps(entries, ensure_ascii=False, indent=2)
    OUT.write_text(
        "// AUTO-GENERATED by scripts/bundle-components.py — DO NOT EDIT BY HAND.\n"
        "//\n"
        "// Inlines every sibling *.dc.html component (every one that does NOT itself\n"
        "// reference components.js — i.e. all except the entry page) so <dc-import>\n"
        "// resolves without a fetch(), which browsers block on file:// origins.\n"
        "// The *.dc.html files are the single source of truth.\n"
        "//\n"
        "// The entry page loads this ONLY on file:// (see its inline guard). Over\n"
        "// http(s) — Pages, `just serve`, Claude Design — the runtime fetches each\n"
        "// *.dc.html live, so a stale bundle can't cause wrong rendering there;\n"
        "// regenerate it to keep the committed artifact diff-clean (CI enforces).\n"
        "//\n"
        "// Regenerate whenever a sibling *.dc.html is added / changed / removed:\n"
        "//   - Full repo checkout:  `just build`  (or `python3 scripts/bundle-components.py`).\n"
        "//     The pre-commit hook also does it. See CONTRIBUTING.md.\n"
        "//   - No shell (design tool, flat dir): rebuild this file by hand to match\n"
        "//     this exact shape — IIFE + `var C` map + loop into window.__resourceBlobs.\n"
        "//     One C entry per sibling *.dc.html that is not the entry page, sorted by\n"
        "//     filename, key \"./\"+filename, value the file's full source as a\n"
        "//     JSON string (2-space indent, non-ASCII kept literal). Do not rename\n"
        "//     the window.__resourceBlobs global — support.js reads it; a different\n"
        "//     name or shape silently no-ops. Full procedure: .claude/CLAUDE.md.\n"
        "(function () {\n"
        "  var C = " + body + ";\n"
        "  window.__resourceBlobs = window.__resourceBlobs || {};\n"
        "  for (var k in C) {\n"
        "    if (!window.__resourceBlobs[k]) {\n"
        "      window.__resourceBlobs[k] = new Blob([C[k]], { type: \"text/html\" });\n"
        "    }\n"
        "  }\n"
        "})();\n",
        encoding="utf-8",
        newline="\n",
    )
    names = ", ".join(p.name for p in COMPONENTS)
    print(f"components.js: bundled {len(COMPONENTS)} component(s) — {names}")


if __name__ == "__main__":
    sys.exit(main())
