#!/usr/bin/env python3
"""Inline sibling Design Component files so the page works from file://.

The entry page (`Platforms.dc.html` in this helper repo; `page.dc.html` in
the vertex-order repos) pulls in sibling components via <dc-import>. The DC
runtime (support.js) resolves those by `fetch()`, which browsers block on
file:// origins ("CORS request not http"). Over http (GitHub Pages,
`just serve`, Claude Design) the fetch works fine, so the entry page loads
`components.js` only when `location.protocol` is `file:` — over http(s) the
runtime always fetches each `*.dc.html` live and a stale bundle can't cause
wrong rendering.

This regenerates `site/components.js` — a plain <script> (loads on
file://) that pre-populates `window.__resourceBlobs[...]` with each
component's source, the cache the runtime checks before it fetches. So
the .dc.html files stay the single source of truth; this is a derived
build artifact, regenerated by the pre-commit hook, `just build`, and
verified in CI by `.github/workflows/check-generated.yml`.

No external deps. Run: python3 scripts/bundle-components.py
"""
import json
import sys
from pathlib import Path

SITE = Path(__file__).resolve().parent.parent / "site"
# The entry page loads this bundle itself over file:// — it must not inline
# itself. In the vertex-order repos the entry page is page.dc.html; this
# platform-icon helper repo uses Platforms.dc.html instead.
ENTRY_PAGE = "Platforms.dc.html"
COMPONENTS = sorted(p for p in SITE.glob("*.dc.html") if p.name != ENTRY_PAGE)
OUT = SITE / "components.js"


def main():
    entries = {}
    for path in COMPONENTS:
        # Key must match support.js ensureFetched(): COMPONENT_DIR ("." ) +
        # "/" + encodeURIComponent(name) + ".dc.html".
        key = "./" + path.name
        entries[key] = path.read_text(encoding="utf-8")

    body = json.dumps(entries, ensure_ascii=False, indent=2)
    OUT.write_text(
        "// AUTO-GENERATED by scripts/bundle-components.py — DO NOT EDIT BY HAND.\n"
        "//\n"
        "// Inlines every sibling *.dc.html component (all except " + ENTRY_PAGE + ") so\n"
        "// <dc-import> resolves without a fetch(), which browsers block on file://\n"
        "// origins. The *.dc.html files are the single source of truth.\n"
        "//\n"
        "// " + ENTRY_PAGE + " loads this ONLY on file:// (see its inline guard). Over\n"
        "// http(s) — Pages, `just serve`, Claude Design — the runtime fetches each\n"
        "// *.dc.html live, so a stale bundle can't cause wrong rendering there;\n"
        "// regenerate it to keep the committed artifact diff-clean (CI enforces).\n"
        "//\n"
        "// Regenerate whenever a sibling *.dc.html is added / changed / removed:\n"
        "//   - Full repo checkout:  `just build`  (or `python3 scripts/bundle-components.py`).\n"
        "//     The pre-commit hook also does it. See CONTRIBUTING.md.\n"
        "//   - No shell (design tool, flat dir): rebuild this file by hand to match\n"
        "//     this exact shape — IIFE + `var C` map + loop into window.__resourceBlobs.\n"
        "//     One C entry per sibling *.dc.html except " + ENTRY_PAGE + ", sorted by\n"
        "//     filename, key \"./\"+filename, value the file's full source as a\n"
        "//     JSON string (2-space indent, non-ASCII kept literal). Do not rename\n"
        "//     the window.__resourceBlobs global — support.js reads it; a different\n"
        "//     name or shape silently no-ops. Full procedure: .claude/CLAUDE.md.\n"
        "(function () {\n"
        "  var C = " + body + ";\n"
        "  window.__resourceBlobs = window.__resourceBlobs || {};\n"
        "  for (var k in C) {\n"
        "    if (!window.__resourceBlobs[k]) {\n"
        "      window.__resourceBlobs[k] = new Blob([C[k]], { type: \"text/html\" });\n"
        "    }\n"
        "  }\n"
        "})();\n",
        encoding="utf-8",
    )
    names = ", ".join(p.name for p in COMPONENTS)
    print(f"components.js: bundled {len(COMPONENTS)} component(s) — {names}")


if __name__ == "__main__":
    sys.exit(main())
